# Generated by Django 3.1.5 on 2021-01-14 23:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_projection_userticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projection',
            name='userTicket',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
