# Generated by Django 3.1.5 on 2021-01-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210115_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projection',
            name='screeningTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
