# Generated by Django 3.1.5 on 2021-01-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210115_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projection',
            name='cinemaHallCapacity',
            field=models.IntegerField(default=20),
        ),
    ]
