# Generated by Django 3.1.5 on 2021-01-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210116_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projection',
            options={'ordering': ['-movieName']},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seatNumber',
            field=models.IntegerField(default=0),
        ),
    ]
