# Generated by Django 3.1.5 on 2021-01-16 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210116_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projection',
            name='userTicket',
        ),
    ]
