# Generated by Django 3.1.5 on 2021-01-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210116_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='movieName',
        ),
        migrations.AddField(
            model_name='ticket',
            name='movieName',
            field=models.ManyToManyField(to='app.Projection'),
        ),
    ]
