# Generated by Django 3.1.5 on 2021-01-17 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210117_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='movieName',
        ),
        migrations.AddField(
            model_name='ticket',
            name='movieName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.projection'),
        ),
    ]
