# Generated by Django 3.1.5 on 2021-01-17 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210117_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projection',
            options={},
        ),
    ]
